const countriesEN = [
  {
    name: "Portugal",
    colors: ["red", "green"],
    continent: "Europe",
    isoCode: "pt",
  },
  {
    name: "Spain",
    colors: ["red", "yellow"],
    continent: "Europe",
    isoCode: "es",
  },
  {
    name: "France",
    colors: ["blue", "white", "red"],
    continent: "Europe",
    isoCode: "fr",
  },
  {
    name: "Germany",
    colors: ["black", "red", "yellow"],
    continent: "Europe",
    isoCode: "de",
  },
  {
    name: "Italy",
    colors: ["green", "white", "red"],
    continent: "Europe",
    isoCode: "it",
  },
  {
    name: "United Kingdom",
    colors: ["red", "white", "blue"],
    continent: "Europe",
    isoCode: "gb",
  },
  {
    name: "Canada",
    colors: ["red", "white"],
    continent: "North America",
    isoCode: "ca",
  },
  {
    name: "United States",
    colors: ["red", "white", "blue"],
    continent: "North America",
    isoCode: "us",
  },
  {
    name: "Brazil",
    colors: ["green", "yellow", "blue"],
    continent: "South America",
    isoCode: "br",
  },
  {
    name: "Australia",
    colors: ["blue", "red", "white"],
    continent: "Oceania",
    isoCode: "au",
  },
  {
    name: "Japan",
    colors: ["red", "white"],
    continent: "Asia",
    isoCode: "jp",
  },
  {
    name: "China",
    colors: ["red", "yellow"],
    continent: "Asia",
    isoCode: "cn",
  },
  {
    name: "India",
    colors: ["orange", "white", "green"],
    continent: "Asia",
    isoCode: "in",
  },
  {
    name: "Mexico",
    colors: ["green", "white", "red"],
    continent: "North America",
    isoCode: "mx",
  },
  {
    name: "Russia",
    colors: ["white", "blue", "red"],
    continent: "Europe/Asia",
    isoCode: "ru",
  },
  {
    name: "South Africa",
    colors: ["black", "green", "yellow", "white", "red", "blue"],
    continent: "Africa",
    isoCode: "za",
  },
  {
    name: "Argentina",
    colors: ["blue", "white"],
    continent: "South America",
    isoCode: "ar",
  },
  {
    name: "Egypt",
    colors: ["black", "white", "red"],
    continent: "Africa",
    isoCode: "eg",
  },
  {
    name: "Turkey",
    colors: ["red", "white"],
    continent: "Europe/Asia",
    isoCode: "tr",
  },
  {
    name: "Indonesia",
    colors: ["red", "white"],
    continent: "Asia",
    isoCode: "id",
  },
  {
    name: "Sweden",
    colors: ["blue", "yellow"],
    continent: "Europe",
    isoCode: "se",
  },
  {
    name: "Finland",
    colors: ["blue", "white"],
    continent: "Europe",
    isoCode: "fi",
  },
  {
    name: "Denmark",
    colors: ["red", "white"],
    continent: "Europe",
    isoCode: "dk",
  },
  {
    name: "Netherlands",
    colors: ["red", "white", "blue"],
    continent: "Europe",
    isoCode: "nl",
  },
  {
    name: "Belgium",
    colors: ["black", "yellow", "red"],
    continent: "Europe",
    isoCode: "be",
  },
  {
    name: "Czech Republic",
    colors: ["white", "red", "blue"],
    continent: "Europe",
    isoCode: "cz",
  },
  {
    name: "Romania",
    colors: ["blue", "yellow", "red"],
    continent: "Europe",
    isoCode: "ro",
  },
  {
    name: "Norway",
    colors: ["red", "white", "blue"],
    continent: "Europe",
    isoCode: "no",
  },
  {
    name: "Switzerland",
    colors: ["red", "white"],
    continent: "Europe",
    isoCode: "ch",
  },
  {
    name: "Austria",
    colors: ["red", "white"],
    continent: "Europe",
    isoCode: "at",
  },
  {
    name: "Poland",
    colors: ["white", "red"],
    continent: "Europe",
    isoCode: "pl",
  },
  {
    name: "Greece",
    colors: ["blue", "white"],
    continent: "Europe",
    isoCode: "gr",
  },
  {
    name: "Ireland",
    colors: ["green", "white", "orange"],
    continent: "Europe",
    isoCode: "ie",
  },
  {
    name: "Hungary",
    colors: ["red", "white", "green"],
    continent: "Europe",
    isoCode: "hu",
  },
  {
    name: "Bulgaria",
    colors: ["white", "green", "red"],
    continent: "Europe",
    isoCode: "bg",
  },
  {
    name: "Estonia",
    colors: ["blue", "black", "white"],
    continent: "Europe",
    isoCode: "ee",
  },
  {
    name: "Latvia",
    colors: ["red", "white"],
    continent: "Europe",
    isoCode: "lv",
  },
  {
    name: "Lithuania",
    colors: ["yellow", "green", "red"],
    continent: "Europe",
    isoCode: "lt",
  },
  {
    name: "Slovakia",
    colors: ["white", "blue", "red"],
    continent: "Europe",
    isoCode: "sk",
  },
  {
    name: "Slovenia",
    colors: ["white", "blue", "green"],
    continent: "Europe",
    isoCode: "si",
  },
  {
    name: "Cyprus",
    colors: ["white", "yellow"],
    continent: "Europe",
    isoCode: "cy",
  },
  {
    name: "Kenya",
    colors: ["black", "red", "green", "white"],
    continent: "Africa",
    isoCode: "ke",
  },
  {
    name: "Nigeria",
    colors: ["green", "white"],
    continent: "Africa",
    isoCode: "ng",
  },
  {
    name: "Morocco",
    colors: ["red", "green"],
    continent: "Africa",
    isoCode: "ma",
  },
  {
    name: "Thailand",
    colors: ["red", "white", "blue"],
    continent: "Asia",
    isoCode: "th",
  },
  {
    name: "Vietnam",
    colors: ["red", "yellow"],
    continent: "Asia",
    isoCode: "vn",
  },
  {
    name: "South Korea",
    colors: ["red", "blue", "white", "black"],
    continent: "Asia",
    isoCode: "kr",
  },
  {
    name: "Chile",
    colors: ["red", "white", "blue"],
    continent: "South America",
    isoCode: "cl",
  },
  {
    name: "Colombia",
    colors: ["yellow", "blue", "red"],
    continent: "South America",
    isoCode: "co",
  },
  {
    name: "Peru",
    colors: ["red", "white", "red"],
    continent: "South America",
    isoCode: "pe",
  },
  {
    name: "New Zealand",
    colors: ["black", "white", "blue"],
    continent: "Oceania",
    isoCode: "nz",
  },
  {
    name: "Cuba",
    colors: ["red", "white", "blue"],
    continent: "North America",
    isoCode: "cu",
  },
  {
    name: "Costa Rica",
    colors: ["blue", "white", "red", "yellow"],
    continent: "North America",
    isoCode: "cr",
  },
  {
    name: "Guatemala",
    colors: ["blue", "white"],
    continent: "North America",
    isoCode: "gt",
  },
  {
    name: "Jamaica",
    colors: ["gold", "black", "green"],
    continent: "North America",
    isoCode: "jm",
  },
  {
    name: "Ukraine",
    colors: ["blue", "yellow"],
    continent: "Europe",
    isoCode: "ua",
  },
  {
    name: "Iceland",
    colors: ["white", "blue", "red"],
    continent: "Europe",
    isoCode: "is",
  },
  {
    name: "Croatia",
    colors: ["red", "white", "blue"],
    continent: "Europe",
    isoCode: "hr",
  },
  {
    name: "Venezuela",
    colors: ["yellow", "blue", "red"],
    continent: "South America",
    isoCode: "ve",
  },
  {
    name: "Ecuador",
    colors: ["yellow", "blue", "red"],
    continent: "South America",
    isoCode: "ec",
  },
  {
    name: "Paraguay",
    colors: ["red", "white", "blue"],
    continent: "South America",
    isoCode: "py",
  },
  {
    name: "Uruguay",
    colors: ["sky blue", "white", "golden yellow"],
    continent: "South America",
    isoCode: "uy",
  },
  {
    name: "Bolivia",
    colors: ["red", "yellow", "green"],
    continent: "South America",
    isoCode: "bo",
  },
  {
    name: "Ghana",
    colors: ["red", "gold", "green", "black"],
    continent: "Africa",
    isoCode: "gh",
  },
  {
    name: "Ethiopia",
    colors: ["green", "yellow", "red"],
    continent: "Africa",
    isoCode: "et",
  },
  {
    name: "Senegal",
    colors: ["green", "yellow", "red"],
    continent: "Africa",
    isoCode: "sn",
  },
  {
    name: "Ivory Coast",
    colors: ["orange", "white", "green"],
    continent: "Africa",
    isoCode: "ci",
  },
  {
    name: "Iran",
    colors: ["green", "white", "red"],
    continent: "Asia",
    isoCode: "ir",
  },
  {
    name: "Israel",
    colors: ["blue", "white"],
    continent: "Asia",
    isoCode: "il",
  },
  {
    name: "Saudi Arabia",
    colors: ["green", "white"],
    continent: "Asia",
    isoCode: "sa",
  },
  {
    name: "United Arab Emirates",
    colors: ["red", "green", "black", "white"],
    continent: "Asia",
    isoCode: "ae",
  },
  {
    name: "Malaysia",
    colors: ["yellow", "black", "red", "white"],
    continent: "Asia",
    isoCode: "my",
  },
  {
    name: "Philippines",
    colors: ["blue", "red", "yellow"],
    continent: "Asia",
    isoCode: "ph",
  },
  {
    name: "Palau",
    colors: ["light blue", "yellow", "red", "black", "white"],
    continent: "Oceania",
    isoCode: "pw",
  },
];