const countries = [
  {
    capital: "Kabul",
    isoCode: "af",
    continent: "Asia",
    flag_1x1: "flags/1x1/af.svg",
    flag_4x3: "flags/4x3/af.svg",
    name: "Afghanistan",
  },
  {
    capital: "Mariehamn",
    isoCode: "ax",
    continent: "Europe",
    flag_1x1: "flags/1x1/ax.svg",
    flag_4x3: "flags/4x3/ax.svg",
    name: "Aland Islands",
  },
  {
    capital: "Tirana",
    isoCode: "al",
    continent: "Europe",
    flag_1x1: "flags/1x1/al.svg",
    flag_4x3: "flags/4x3/al.svg",
    name: "Albania",
  },
  {
    capital: "Algiers",
    isoCode: "dz",
    continent: "Africa",
    flag_1x1: "flags/1x1/dz.svg",
    flag_4x3: "flags/4x3/dz.svg",
    name: "Algeria",
  },
  {
    capital: "Pago Pago",
    isoCode: "as",
    continent: "Oceania",
    flag_1x1: "flags/1x1/as.svg",
    flag_4x3: "flags/4x3/as.svg",
    name: "American Samoa",
  },
  {
    capital: "Andorra la Vella",
    isoCode: "ad",
    continent: "Europe",
    flag_1x1: "flags/1x1/ad.svg",
    flag_4x3: "flags/4x3/ad.svg",
    name: "Andorra",
  },
  {
    capital: "Luanda",
    isoCode: "ao",
    continent: "Africa",
    flag_1x1: "flags/1x1/ao.svg",
    flag_4x3: "flags/4x3/ao.svg",
    name: "Angola",
  },
  {
    capital: "The Valley",
    isoCode: "ai",
    continent: "North America",
    flag_1x1: "flags/1x1/ai.svg",
    flag_4x3: "flags/4x3/ai.svg",
    name: "Anguilla",
  },
  {
    isoCode: "aq",
    continent: "Antarctica",
    flag_1x1: "flags/1x1/aq.svg",
    flag_4x3: "flags/4x3/aq.svg",
    name: "Antarctica",
  },
  {
    capital: "St. John's",
    isoCode: "ag",
    continent: "North America",
    flag_1x1: "flags/1x1/ag.svg",
    flag_4x3: "flags/4x3/ag.svg",
    name: "Antigua and Barbuda",
  },
  {
    capital: "Buenos Aires",
    isoCode: "ar",
    continent: "South America",
    flag_1x1: "flags/1x1/ar.svg",
    flag_4x3: "flags/4x3/ar.svg",
    name: "Argentina",
  },
  {
    capital: "Yerevan",
    isoCode: "am",
    continent: "Asia",
    flag_1x1: "flags/1x1/am.svg",
    flag_4x3: "flags/4x3/am.svg",
    name: "Armenia",
  },
  {
    capital: "Oranjestad",
    isoCode: "aw",
    continent: "South America",
    flag_1x1: "flags/1x1/aw.svg",
    flag_4x3: "flags/4x3/aw.svg",
    name: "Aruba",
  },
  {
    capital: "Canberra",
    isoCode: "au",
    continent: "Oceania",
    flag_1x1: "flags/1x1/au.svg",
    flag_4x3: "flags/4x3/au.svg",
    name: "Australia",
  },
  {
    capital: "Vienna",
    isoCode: "at",
    continent: "Europe",
    flag_1x1: "flags/1x1/at.svg",
    flag_4x3: "flags/4x3/at.svg",
    name: "Austria",
  },
  {
    capital: "Baku",
    isoCode: "az",
    continent: "Asia",
    flag_1x1: "flags/1x1/az.svg",
    flag_4x3: "flags/4x3/az.svg",
    name: "Azerbaijan",
  },
  {
    capital: "Nassau",
    isoCode: "bs",
    continent: "North America",
    flag_1x1: "flags/1x1/bs.svg",
    flag_4x3: "flags/4x3/bs.svg",
    name: "Bahamas",
  },
  {
    capital: "Manama",
    isoCode: "bh",
    continent: "Asia",
    flag_1x1: "flags/1x1/bh.svg",
    flag_4x3: "flags/4x3/bh.svg",
    name: "Bahrain",
  },
  {
    capital: "Dhaka",
    isoCode: "bd",
    continent: "Asia",
    flag_1x1: "flags/1x1/bd.svg",
    flag_4x3: "flags/4x3/bd.svg",
    name: "Bangladesh",
  },
  {
    capital: "Bridgetown",
    isoCode: "bb",
    continent: "North America",
    flag_1x1: "flags/1x1/bb.svg",
    flag_4x3: "flags/4x3/bb.svg",
    name: "Barbados",
  },
  {
    capital: "Minsk",
    isoCode: "by",
    continent: "Europe",
    flag_1x1: "flags/1x1/by.svg",
    flag_4x3: "flags/4x3/by.svg",
    name: "Belarus",
  },
  {
    capital: "Brussels",
    isoCode: "be",
    continent: "Europe",
    flag_1x1: "flags/1x1/be.svg",
    flag_4x3: "flags/4x3/be.svg",
    name: "Belgium",
  },
  {
    capital: "Belmopan",
    isoCode: "bz",
    continent: "North America",
    flag_1x1: "flags/1x1/bz.svg",
    flag_4x3: "flags/4x3/bz.svg",
    name: "Belize",
  },
  {
    capital: "Porto-Novo",
    isoCode: "bj",
    continent: "Africa",
    flag_1x1: "flags/1x1/bj.svg",
    flag_4x3: "flags/4x3/bj.svg",
    name: "Benin",
  },
  {
    capital: "Hamilton",
    isoCode: "bm",
    continent: "North America",
    flag_1x1: "flags/1x1/bm.svg",
    flag_4x3: "flags/4x3/bm.svg",
    name: "Bermuda",
  },
  {
    capital: "Thimphu",
    isoCode: "bt",
    continent: "Asia",
    flag_1x1: "flags/1x1/bt.svg",
    flag_4x3: "flags/4x3/bt.svg",
    name: "Bhutan",
  },
  {
    capital: "Sucre",
    isoCode: "bo",
    continent: "South America",
    flag_1x1: "flags/1x1/bo.svg",
    flag_4x3: "flags/4x3/bo.svg",
    name: "Bolivia",
  },
  {
    capital: "Kralendijk",
    isoCode: "bq",
    continent: "South America",
    flag_1x1: "flags/1x1/bq.svg",
    flag_4x3: "flags/4x3/bq.svg",
    name: "Bonaire, Sint Eustatius and Saba",
  },
  {
    capital: "Sarajevo",
    isoCode: "ba",
    continent: "Europe",
    flag_1x1: "flags/1x1/ba.svg",
    flag_4x3: "flags/4x3/ba.svg",
    name: "Bosnia and Herzegovina",
  },
  {
    capital: "Gaborone",
    isoCode: "bw",
    continent: "Africa",
    flag_1x1: "flags/1x1/bw.svg",
    flag_4x3: "flags/4x3/bw.svg",
    name: "Botswana",
  },
  {
    capital: "Brasília",
    isoCode: "br",
    continent: "South America",
    flag_1x1: "flags/1x1/br.svg",
    flag_4x3: "flags/4x3/br.svg",
    name: "Brazil",
  },
  {
    capital: "Diego Garcia",
    isoCode: "io",
    continent: "Asia",
    flag_1x1: "flags/1x1/io.svg",
    flag_4x3: "flags/4x3/io.svg",
    name: "British Indian Ocean Territory",
  },
  {
    capital: "Bandar Seri Begawan",
    isoCode: "bn",
    continent: "Asia",
    flag_1x1: "flags/1x1/bn.svg",
    flag_4x3: "flags/4x3/bn.svg",
    name: "Brunei Darussalam",
  },
  {
    capital: "Sofia",
    isoCode: "bg",
    continent: "Europe",
    flag_1x1: "flags/1x1/bg.svg",
    flag_4x3: "flags/4x3/bg.svg",
    name: "Bulgaria",
  },
  {
    capital: "Ouagadougou",
    isoCode: "bf",
    continent: "Africa",
    flag_1x1: "flags/1x1/bf.svg",
    flag_4x3: "flags/4x3/bf.svg",
    name: "Burkina Faso",
  },
  {
    capital: "Bujumbura",
    isoCode: "bi",
    continent: "Africa",
    flag_1x1: "flags/1x1/bi.svg",
    flag_4x3: "flags/4x3/bi.svg",
    name: "Burundi",
  },
  {
    capital: "Praia",
    isoCode: "cv",
    continent: "Africa",
    flag_1x1: "flags/1x1/cv.svg",
    flag_4x3: "flags/4x3/cv.svg",
    name: "Cabo Verde",
  },
  {
    capital: "Phnom Penh",
    isoCode: "kh",
    continent: "Asia",
    flag_1x1: "flags/1x1/kh.svg",
    flag_4x3: "flags/4x3/kh.svg",
    name: "Cambodia",
  },
  {
    capital: "Yaoundé",
    isoCode: "cm",
    continent: "Africa",
    flag_1x1: "flags/1x1/cm.svg",
    flag_4x3: "flags/4x3/cm.svg",
    name: "Cameroon",
  },
  {
    capital: "Ottawa",
    isoCode: "ca",
    continent: "North America",
    flag_1x1: "flags/1x1/ca.svg",
    flag_4x3: "flags/4x3/ca.svg",
    name: "Canada",
  },
  {
    isoCode: "ic",
    continent: "Europe",
    flag_1x1: "flags/1x1/ic.svg",
    flag_4x3: "flags/4x3/ic.svg",
    name: "Canary Islands",
  },
  {
    capital: "George Town",
    isoCode: "ky",
    continent: "North America",
    flag_1x1: "flags/1x1/ky.svg",
    flag_4x3: "flags/4x3/ky.svg",
    name: "Cayman Islands",
  },
  {
    capital: "Bangui",
    isoCode: "cf",
    continent: "Africa",
    flag_1x1: "flags/1x1/cf.svg",
    flag_4x3: "flags/4x3/cf.svg",
    name: "Central African Republic",
  },
  {
    capital: "N'Djamena",
    isoCode: "td",
    continent: "Africa",
    flag_1x1: "flags/1x1/td.svg",
    flag_4x3: "flags/4x3/td.svg",
    name: "Chad",
  },
  {
    capital: "Santiago",
    isoCode: "cl",
    continent: "South America",
    flag_1x1: "flags/1x1/cl.svg",
    flag_4x3: "flags/4x3/cl.svg",
    name: "Chile",
  },
  {
    capital: "Beijing",
    isoCode: "cn",
    continent: "Asia",
    flag_1x1: "flags/1x1/cn.svg",
    flag_4x3: "flags/4x3/cn.svg",
    name: "China",
  },
  {
    capital: "Flying Fish Cove",
    isoCode: "cx",
    continent: "Asia",
    flag_1x1: "flags/1x1/cx.svg",
    flag_4x3: "flags/4x3/cx.svg",
    name: "Christmas Island",
  },
  {
    capital: "West Island",
    isoCode: "cc",
    continent: "Asia",
    flag_1x1: "flags/1x1/cc.svg",
    flag_4x3: "flags/4x3/cc.svg",
    name: "Cocos (Keeling) Islands",
  },
  {
    capital: "Bogotá",
    isoCode: "co",
    continent: "South America",
    flag_1x1: "flags/1x1/co.svg",
    flag_4x3: "flags/4x3/co.svg",
    name: "Colombia",
  },
  {
    capital: "Moroni",
    isoCode: "km",
    continent: "Africa",
    flag_1x1: "flags/1x1/km.svg",
    flag_4x3: "flags/4x3/km.svg",
    name: "Comoros",
  },
  {
    capital: "Avarua",
    isoCode: "ck",
    continent: "Oceania",
    flag_1x1: "flags/1x1/ck.svg",
    flag_4x3: "flags/4x3/ck.svg",
    name: "Cook Islands",
  },
  {
    capital: "San José",
    isoCode: "cr",
    continent: "North America",
    flag_1x1: "flags/1x1/cr.svg",
    flag_4x3: "flags/4x3/cr.svg",
    name: "Costa Rica",
  },
  {
    capital: "Zagreb",
    isoCode: "hr",
    continent: "Europe",
    flag_1x1: "flags/1x1/hr.svg",
    flag_4x3: "flags/4x3/hr.svg",
    name: "Croatia",
  },
  {
    capital: "Havana",
    isoCode: "cu",
    continent: "North America",
    flag_1x1: "flags/1x1/cu.svg",
    flag_4x3: "flags/4x3/cu.svg",
    name: "Cuba",
  },
  {
    capital: "Willemstad",
    isoCode: "cw",
    continent: "South America",
    flag_1x1: "flags/1x1/cw.svg",
    flag_4x3: "flags/4x3/cw.svg",
    name: "Curaçao",
  },
  {
    capital: "Nicosia",
    isoCode: "cy",
    continent: "Europe",
    flag_1x1: "flags/1x1/cy.svg",
    flag_4x3: "flags/4x3/cy.svg",
    name: "Cyprus",
  },
  {
    capital: "Prague",
    isoCode: "cz",
    continent: "Europe",
    flag_1x1: "flags/1x1/cz.svg",
    flag_4x3: "flags/4x3/cz.svg",
    name: "Czech Republic",
  },
  {
    capital: "Yamoussoukro",
    isoCode: "ci",
    continent: "Africa",
    flag_1x1: "flags/1x1/ci.svg",
    flag_4x3: "flags/4x3/ci.svg",
    name: "Côte d'Ivoire",
  },
  {
    capital: "Kinshasa",
    isoCode: "cd",
    continent: "Africa",
    flag_1x1: "flags/1x1/cd.svg",
    flag_4x3: "flags/4x3/cd.svg",
    name: "Democratic Republic of the Congo",
  },
  {
    capital: "Copenhagen",
    isoCode: "dk",
    continent: "Europe",
    flag_1x1: "flags/1x1/dk.svg",
    flag_4x3: "flags/4x3/dk.svg",
    name: "Denmark",
  },
  {
    capital: "Djibouti",
    isoCode: "dj",
    continent: "Africa",
    flag_1x1: "flags/1x1/dj.svg",
    flag_4x3: "flags/4x3/dj.svg",
    name: "Djibouti",
  },
  {
    capital: "Roseau",
    isoCode: "dm",
    continent: "North America",
    flag_1x1: "flags/1x1/dm.svg",
    flag_4x3: "flags/4x3/dm.svg",
    name: "Dominica",
  },
  {
    capital: "Santo Domingo",
    isoCode: "do",
    continent: "North America",
    flag_1x1: "flags/1x1/do.svg",
    flag_4x3: "flags/4x3/do.svg",
    name: "Dominican Republic",
  },
  {
    capital: "Quito",
    isoCode: "ec",
    continent: "South America",
    flag_1x1: "flags/1x1/ec.svg",
    flag_4x3: "flags/4x3/ec.svg",
    name: "Ecuador",
  },
  {
    capital: "Cairo",
    isoCode: "eg",
    continent: "Africa",
    flag_1x1: "flags/1x1/eg.svg",
    flag_4x3: "flags/4x3/eg.svg",
    name: "Egypt",
  },
  {
    capital: "San Salvador",
    isoCode: "sv",
    continent: "North America",
    flag_1x1: "flags/1x1/sv.svg",
    flag_4x3: "flags/4x3/sv.svg",
    name: "El Salvador",
  },
  {
    capital: "London",
    isoCode: "gb-eng",
    continent: "Europe",
    flag_1x1: "flags/1x1/gb-eng.svg",
    flag_4x3: "flags/4x3/gb-eng.svg",
    name: "England",
  },
  {
    capital: "Malabo",
    isoCode: "gq",
    continent: "Africa",
    flag_1x1: "flags/1x1/gq.svg",
    flag_4x3: "flags/4x3/gq.svg",
    name: "Equatorial Guinea",
  },
  {
    capital: "Asmara",
    isoCode: "er",
    continent: "Africa",
    flag_1x1: "flags/1x1/er.svg",
    flag_4x3: "flags/4x3/er.svg",
    name: "Eritrea",
  },
  {
    capital: "Tallinn",
    isoCode: "ee",
    continent: "Europe",
    flag_1x1: "flags/1x1/ee.svg",
    flag_4x3: "flags/4x3/ee.svg",
    name: "Estonia",
  },
  {
    capital: "Lobamba, Mbabane",
    isoCode: "sz",
    continent: "Africa",
    flag_1x1: "flags/1x1/sz.svg",
    flag_4x3: "flags/4x3/sz.svg",
    name: "Eswatini",
  },
  {
    capital: "Addis Ababa",
    isoCode: "et",
    continent: "Africa",
    flag_1x1: "flags/1x1/et.svg",
    flag_4x3: "flags/4x3/et.svg",
    name: "Ethiopia",
  },
  {
    isoCode: "eu",
    continent: "Europe",
    flag_1x1: "flags/1x1/eu.svg",
    flag_4x3: "flags/4x3/eu.svg",
    name: "Europe",
  },
  {
    capital: "Stanley",
    isoCode: "fk",
    continent: "South America",
    flag_1x1: "flags/1x1/fk.svg",
    flag_4x3: "flags/4x3/fk.svg",
    name: "Falkland Islands",
  },
  {
    capital: "Tórshavn",
    isoCode: "fo",
    continent: "Europe",
    flag_1x1: "flags/1x1/fo.svg",
    flag_4x3: "flags/4x3/fo.svg",
    name: "Faroe Islands",
  },
  {
    capital: "Palikir",
    isoCode: "fm",
    continent: "Oceania",
    flag_1x1: "flags/1x1/fm.svg",
    flag_4x3: "flags/4x3/fm.svg",
    name: "Federated States of Micronesia",
  },
  {
    capital: "Suva",
    isoCode: "fj",
    continent: "Oceania",
    flag_1x1: "flags/1x1/fj.svg",
    flag_4x3: "flags/4x3/fj.svg",
    name: "Fiji",
  },
  {
    capital: "Helsinki",
    isoCode: "fi",
    continent: "Europe",
    flag_1x1: "flags/1x1/fi.svg",
    flag_4x3: "flags/4x3/fi.svg",
    name: "Finland",
  },
  {
    capital: "Paris",
    isoCode: "fr",
    continent: "Europe",
    flag_1x1: "flags/1x1/fr.svg",
    flag_4x3: "flags/4x3/fr.svg",
    name: "France",
  },
  {
    capital: "Cayenne",
    isoCode: "gf",
    continent: "South America",
    flag_1x1: "flags/1x1/gf.svg",
    flag_4x3: "flags/4x3/gf.svg",
    name: "French Guiana",
  },
  {
    capital: "Papeete",
    isoCode: "pf",
    continent: "Oceania",
    flag_1x1: "flags/1x1/pf.svg",
    flag_4x3: "flags/4x3/pf.svg",
    name: "French Polynesia",
  },
  {
    capital: "Libreville",
    isoCode: "ga",
    continent: "Africa",
    flag_1x1: "flags/1x1/ga.svg",
    flag_4x3: "flags/4x3/ga.svg",
    name: "Gabon",
  },
  {
    capital: "Banjul",
    isoCode: "gm",
    continent: "Africa",
    flag_1x1: "flags/1x1/gm.svg",
    flag_4x3: "flags/4x3/gm.svg",
    name: "Gambia",
  },
  {
    capital: "Tbilisi",
    isoCode: "ge",
    continent: "Asia",
    flag_1x1: "flags/1x1/ge.svg",
    flag_4x3: "flags/4x3/ge.svg",
    name: "Georgia",
  },
  {
    capital: "Berlin",
    isoCode: "de",
    continent: "Europe",
    flag_1x1: "flags/1x1/de.svg",
    flag_4x3: "flags/4x3/de.svg",
    name: "Germany",
  },
  {
    capital: "Accra",
    isoCode: "gh",
    continent: "Africa",
    flag_1x1: "flags/1x1/gh.svg",
    flag_4x3: "flags/4x3/gh.svg",
    name: "Ghana",
  },
  {
    capital: "Gibraltar",
    isoCode: "gi",
    continent: "Europe",
    flag_1x1: "flags/1x1/gi.svg",
    flag_4x3: "flags/4x3/gi.svg",
    name: "Gibraltar",
  },
  {
    capital: "Athens",
    isoCode: "gr",
    continent: "Europe",
    flag_1x1: "flags/1x1/gr.svg",
    flag_4x3: "flags/4x3/gr.svg",
    name: "Greece",
  },
  {
    capital: "Nuuk",
    isoCode: "gl",
    continent: "North America",
    flag_1x1: "flags/1x1/gl.svg",
    flag_4x3: "flags/4x3/gl.svg",
    name: "Greenland",
  },
  {
    capital: "St. George's",
    isoCode: "gd",
    continent: "North America",
    flag_1x1: "flags/1x1/gd.svg",
    flag_4x3: "flags/4x3/gd.svg",
    name: "Grenada",
  },
  {
    capital: "Basse-Terre",
    isoCode: "gp",
    continent: "North America",
    flag_1x1: "flags/1x1/gp.svg",
    flag_4x3: "flags/4x3/gp.svg",
    name: "Guadeloupe",
  },
  {
    capital: "Hagåtña",
    isoCode: "gu",
    continent: "Oceania",
    flag_1x1: "flags/1x1/gu.svg",
    flag_4x3: "flags/4x3/gu.svg",
    name: "Guam",
  },
  {
    capital: "Guatemala City",
    isoCode: "gt",
    continent: "North America",
    flag_1x1: "flags/1x1/gt.svg",
    flag_4x3: "flags/4x3/gt.svg",
    name: "Guatemala",
  },
  {
    capital: "Saint Peter Port",
    isoCode: "gg",
    continent: "Europe",
    flag_1x1: "flags/1x1/gg.svg",
    flag_4x3: "flags/4x3/gg.svg",
    name: "Guernsey",
  },
  {
    capital: "Conakry",
    isoCode: "gn",
    continent: "Africa",
    flag_1x1: "flags/1x1/gn.svg",
    flag_4x3: "flags/4x3/gn.svg",
    name: "Guinea",
  },
  {
    capital: "Bissau",
    isoCode: "gw",
    continent: "Africa",
    flag_1x1: "flags/1x1/gw.svg",
    flag_4x3: "flags/4x3/gw.svg",
    name: "Guinea-Bissau",
  },
  {
    capital: "Georgetown",
    isoCode: "gy",
    continent: "South America",
    flag_1x1: "flags/1x1/gy.svg",
    flag_4x3: "flags/4x3/gy.svg",
    name: "Guyana",
  },
  {
    capital: "Port-au-Prince",
    isoCode: "ht",
    continent: "North America",
    flag_1x1: "flags/1x1/ht.svg",
    flag_4x3: "flags/4x3/ht.svg",
    name: "Haiti",
  },
  {
    capital: "Vatican City",
    isoCode: "va",
    continent: "Europe",
    flag_1x1: "flags/1x1/va.svg",
    flag_4x3: "flags/4x3/va.svg",
    name: "Holy See",
  },
  {
    capital: "Tegucigalpa",
    isoCode: "hn",
    continent: "North America",
    flag_1x1: "flags/1x1/hn.svg",
    flag_4x3: "flags/4x3/hn.svg",
    name: "Honduras",
  },
  {
    capital: "Hong Kong",
    isoCode: "hk",
    continent: "Asia",
    flag_1x1: "flags/1x1/hk.svg",
    flag_4x3: "flags/4x3/hk.svg",
    name: "Hong Kong",
  },
  {
    capital: "Budapest",
    isoCode: "hu",
    continent: "Europe",
    flag_1x1: "flags/1x1/hu.svg",
    flag_4x3: "flags/4x3/hu.svg",
    name: "Hungary",
  },
  {
    capital: "Reykjavik",
    isoCode: "is",
    continent: "Europe",
    flag_1x1: "flags/1x1/is.svg",
    flag_4x3: "flags/4x3/is.svg",
    name: "Iceland",
  },
  {
    capital: "New Delhi",
    isoCode: "in",
    continent: "Asia",
    flag_1x1: "flags/1x1/in.svg",
    flag_4x3: "flags/4x3/in.svg",
    name: "India",
  },
  {
    capital: "Jakarta",
    isoCode: "id",
    continent: "Asia",
    flag_1x1: "flags/1x1/id.svg",
    flag_4x3: "flags/4x3/id.svg",
    name: "Indonesia",
  },
  {
    capital: "Tehran",
    isoCode: "ir",
    continent: "Asia",
    flag_1x1: "flags/1x1/ir.svg",
    flag_4x3: "flags/4x3/ir.svg",
    name: "Iran",
  },
  {
    capital: "Baghdad",
    isoCode: "iq",
    continent: "Asia",
    flag_1x1: "flags/1x1/iq.svg",
    flag_4x3: "flags/4x3/iq.svg",
    name: "Iraq",
  },
  {
    capital: "Dublin",
    isoCode: "ie",
    continent: "Europe",
    flag_1x1: "flags/1x1/ie.svg",
    flag_4x3: "flags/4x3/ie.svg",
    name: "Ireland",
  },
  {
    capital: "Douglas",
    isoCode: "im",
    continent: "Europe",
    flag_1x1: "flags/1x1/im.svg",
    flag_4x3: "flags/4x3/im.svg",
    name: "Isle of Man",
  },
  {
    capital: "Jerusalem",
    isoCode: "il",
    continent: "Asia",
    flag_1x1: "flags/1x1/il.svg",
    flag_4x3: "flags/4x3/il.svg",
    name: "Israel",
  },
  {
    capital: "Rome",
    isoCode: "it",
    continent: "Europe",
    flag_1x1: "flags/1x1/it.svg",
    flag_4x3: "flags/4x3/it.svg",
    name: "Italy",
  },
  {
    capital: "Kingston",
    isoCode: "jm",
    continent: "North America",
    flag_1x1: "flags/1x1/jm.svg",
    flag_4x3: "flags/4x3/jm.svg",
    name: "Jamaica",
  },
  {
    capital: "Tokyo",
    isoCode: "jp",
    continent: "Asia",
    flag_1x1: "flags/1x1/jp.svg",
    flag_4x3: "flags/4x3/jp.svg",
    name: "Japan",
  },
  {
    capital: "Saint Helier",
    isoCode: "je",
    continent: "Europe",
    flag_1x1: "flags/1x1/je.svg",
    flag_4x3: "flags/4x3/je.svg",
    name: "Jersey",
  },
  {
    capital: "Amman",
    isoCode: "jo",
    continent: "Asia",
    flag_1x1: "flags/1x1/jo.svg",
    flag_4x3: "flags/4x3/jo.svg",
    name: "Jordan",
  },
  {
    capital: "Astana",
    isoCode: "kz",
    continent: "Asia",
    flag_1x1: "flags/1x1/kz.svg",
    flag_4x3: "flags/4x3/kz.svg",
    name: "Kazakhstan",
  },
  {
    capital: "Nairobi",
    isoCode: "ke",
    continent: "Africa",
    flag_1x1: "flags/1x1/ke.svg",
    flag_4x3: "flags/4x3/ke.svg",
    name: "Kenya",
  },
  {
    capital: "South Tarawa",
    isoCode: "ki",
    continent: "Oceania",
    flag_1x1: "flags/1x1/ki.svg",
    flag_4x3: "flags/4x3/ki.svg",
    name: "Kiribati",
  },
  {
    capital: "Pristina",
    isoCode: "xk",
    continent: "Europe",
    flag_1x1: "flags/1x1/xk.svg",
    flag_4x3: "flags/4x3/xk.svg",
    name: "Kosovo",
  },
  {
    capital: "Kuwait City",
    isoCode: "kw",
    continent: "Asia",
    flag_1x1: "flags/1x1/kw.svg",
    flag_4x3: "flags/4x3/kw.svg",
    name: "Kuwait",
  },
  {
    capital: "Bishkek",
    isoCode: "kg",
    continent: "Asia",
    flag_1x1: "flags/1x1/kg.svg",
    flag_4x3: "flags/4x3/kg.svg",
    name: "Kyrgyzstan",
  },
  {
    capital: "Vientiane",
    isoCode: "la",
    continent: "Asia",
    flag_1x1: "flags/1x1/la.svg",
    flag_4x3: "flags/4x3/la.svg",
    name: "Laos",
  },
  {
    capital: "Riga",
    isoCode: "lv",
    continent: "Europe",
    flag_1x1: "flags/1x1/lv.svg",
    flag_4x3: "flags/4x3/lv.svg",
    name: "Latvia",
  },
  {
    capital: "Beirut",
    isoCode: "lb",
    continent: "Asia",
    flag_1x1: "flags/1x1/lb.svg",
    flag_4x3: "flags/4x3/lb.svg",
    name: "Lebanon",
  },
  {
    capital: "Maseru",
    isoCode: "ls",
    continent: "Africa",
    flag_1x1: "flags/1x1/ls.svg",
    flag_4x3: "flags/4x3/ls.svg",
    name: "Lesotho",
  },
  {
    capital: "Monrovia",
    isoCode: "lr",
    continent: "Africa",
    flag_1x1: "flags/1x1/lr.svg",
    flag_4x3: "flags/4x3/lr.svg",
    name: "Liberia",
  },
  {
    capital: "Tripoli",
    isoCode: "ly",
    continent: "Africa",
    flag_1x1: "flags/1x1/ly.svg",
    flag_4x3: "flags/4x3/ly.svg",
    name: "Libya",
  },
  {
    capital: "Vaduz",
    isoCode: "li",
    continent: "Europe",
    flag_1x1: "flags/1x1/li.svg",
    flag_4x3: "flags/4x3/li.svg",
    name: "Liechtenstein",
  },
  {
    capital: "Vilnius",
    isoCode: "lt",
    continent: "Europe",
    flag_1x1: "flags/1x1/lt.svg",
    flag_4x3: "flags/4x3/lt.svg",
    name: "Lithuania",
  },
  {
    capital: "Luxembourg City",
    isoCode: "lu",
    continent: "Europe",
    flag_1x1: "flags/1x1/lu.svg",
    flag_4x3: "flags/4x3/lu.svg",
    name: "Luxembourg",
  },
  {
    capital: "Macau",
    isoCode: "mo",
    continent: "Asia",
    flag_1x1: "flags/1x1/mo.svg",
    flag_4x3: "flags/4x3/mo.svg",
    name: "Macau",
  },
  {
    capital: "Antananarivo",
    isoCode: "mg",
    continent: "Africa",
    flag_1x1: "flags/1x1/mg.svg",
    flag_4x3: "flags/4x3/mg.svg",
    name: "Madagascar",
  },
  {
    isoCode: "mad",
    continent: "Europe",
    flag_1x1: "flags/1x1/mad.svg",
    flag_4x3: "flags/4x3/mad.svg",
    name: "Madeira Islands",
  },
  {
    capital: "Lilongwe",
    isoCode: "mw",
    continent: "Africa",
    flag_1x1: "flags/1x1/mw.svg",
    flag_4x3: "flags/4x3/mw.svg",
    name: "Malawi",
  },
  {
    capital: "Kuala Lumpur",
    isoCode: "my",
    continent: "Asia",
    flag_1x1: "flags/1x1/my.svg",
    flag_4x3: "flags/4x3/my.svg",
    name: "Malaysia",
  },
  {
    capital: "Malé",
    isoCode: "mv",
    continent: "Asia",
    flag_1x1: "flags/1x1/mv.svg",
    flag_4x3: "flags/4x3/mv.svg",
    name: "Maldives",
  },
  {
    capital: "Bamako",
    isoCode: "ml",
    continent: "Africa",
    flag_1x1: "flags/1x1/ml.svg",
    flag_4x3: "flags/4x3/ml.svg",
    name: "Mali",
  },
  {
    capital: "Valletta",
    isoCode: "mt",
    continent: "Europe",
    flag_1x1: "flags/1x1/mt.svg",
    flag_4x3: "flags/4x3/mt.svg",
    name: "Malta",
  },
  {
    capital: "Majuro",
    isoCode: "mh",
    continent: "Oceania",
    flag_1x1: "flags/1x1/mh.svg",
    flag_4x3: "flags/4x3/mh.svg",
    name: "Marshall Islands",
  },
  {
    capital: "Fort-de-France",
    isoCode: "mq",
    continent: "North America",
    flag_1x1: "flags/1x1/mq.svg",
    flag_4x3: "flags/4x3/mq.svg",
    name: "Martinique",
  },
  {
    capital: "Nouakchott",
    isoCode: "mr",
    continent: "Africa",
    flag_1x1: "flags/1x1/mr.svg",
    flag_4x3: "flags/4x3/mr.svg",
    name: "Mauritania",
  },
  {
    capital: "Port Louis",
    isoCode: "mu",
    continent: "Africa",
    flag_1x1: "flags/1x1/mu.svg",
    flag_4x3: "flags/4x3/mu.svg",
    name: "Mauritius",
  },
  {
    capital: "Mamoudzou",
    isoCode: "yt",
    continent: "Africa",
    flag_1x1: "flags/1x1/yt.svg",
    flag_4x3: "flags/4x3/yt.svg",
    name: "Mayotte",
  },
  {
    capital: "Mexico City",
    isoCode: "mx",
    continent: "North America",
    flag_1x1: "flags/1x1/mx.svg",
    flag_4x3: "flags/4x3/mx.svg",
    name: "Mexico",
  },
  {
    capital: "Chișinău",
    isoCode: "md",
    continent: "Europe",
    flag_1x1: "flags/1x1/md.svg",
    flag_4x3: "flags/4x3/md.svg",
    name: "Moldova",
  },
  {
    capital: "Monaco",
    isoCode: "mc",
    continent: "Europe",
    flag_1x1: "flags/1x1/mc.svg",
    flag_4x3: "flags/4x3/mc.svg",
    name: "Monaco",
  },
  {
    capital: "Ulaanbaatar",
    isoCode: "mn",
    continent: "Asia",
    flag_1x1: "flags/1x1/mn.svg",
    flag_4x3: "flags/4x3/mn.svg",
    name: "Mongolia",
  },
  {
    capital: "Podgorica",
    isoCode: "me",
    continent: "Europe",
    flag_1x1: "flags/1x1/me.svg",
    flag_4x3: "flags/4x3/me.svg",
    name: "Montenegro",
  },
  {
    capital: "Little Bay, Brades, Plymouth",
    isoCode: "ms",
    continent: "North America",
    flag_1x1: "flags/1x1/ms.svg",
    flag_4x3: "flags/4x3/ms.svg",
    name: "Montserrat",
  },
  {
    capital: "Rabat",
    isoCode: "ma",
    continent: "Africa",
    flag_1x1: "flags/1x1/ma.svg",
    flag_4x3: "flags/4x3/ma.svg",
    name: "Morocco",
  },
  {
    capital: "Maputo",
    isoCode: "mz",
    continent: "Africa",
    flag_1x1: "flags/1x1/mz.svg",
    flag_4x3: "flags/4x3/mz.svg",
    name: "Mozambique",
  },
  {
    capital: "Naypyidaw",
    isoCode: "mm",
    continent: "Asia",
    flag_1x1: "flags/1x1/mm.svg",
    flag_4x3: "flags/4x3/mm.svg",
    name: "Myanmar",
  },
  {
    capital: "Windhoek",
    isoCode: "na",
    continent: "Africa",
    flag_1x1: "flags/1x1/na.svg",
    flag_4x3: "flags/4x3/na.svg",
    name: "Namibia",
  },
  {
    capital: "Yaren District",
    isoCode: "nr",
    continent: "Oceania",
    flag_1x1: "flags/1x1/nr.svg",
    flag_4x3: "flags/4x3/nr.svg",
    name: "Nauru",
  },
  {
    capital: "Kathmandu",
    isoCode: "np",
    continent: "Asia",
    flag_1x1: "flags/1x1/np.svg",
    flag_4x3: "flags/4x3/np.svg",
    name: "Nepal",
  },
  {
    capital: "Amsterdam",
    isoCode: "nl",
    continent: "Europe",
    flag_1x1: "flags/1x1/nl.svg",
    flag_4x3: "flags/4x3/nl.svg",
    name: "Netherlands",
  },
  {
    capital: "Nouméa",
    isoCode: "nc",
    continent: "Oceania",
    flag_1x1: "flags/1x1/nc.svg",
    flag_4x3: "flags/4x3/nc.svg",
    name: "New Caledonia",
  },
  {
    capital: "Wellington",
    isoCode: "nz",
    continent: "Oceania",
    flag_1x1: "flags/1x1/nz.svg",
    flag_4x3: "flags/4x3/nz.svg",
    name: "New Zealand",
  },
  {
    capital: "Managua",
    isoCode: "ni",
    continent: "North America",
    flag_1x1: "flags/1x1/ni.svg",
    flag_4x3: "flags/4x3/ni.svg",
    name: "Nicaragua",
  },
  {
    capital: "Niamey",
    isoCode: "ne",
    continent: "Africa",
    flag_1x1: "flags/1x1/ne.svg",
    flag_4x3: "flags/4x3/ne.svg",
    name: "Niger",
  },
  {
    capital: "Abuja",
    isoCode: "ng",
    continent: "Africa",
    flag_1x1: "flags/1x1/ng.svg",
    flag_4x3: "flags/4x3/ng.svg",
    name: "Nigeria",
  },
  {
    capital: "Alofi",
    isoCode: "nu",
    continent: "Oceania",
    flag_1x1: "flags/1x1/nu.svg",
    flag_4x3: "flags/4x3/nu.svg",
    name: "Niue",
  },
  {
    capital: "Kingston",
    isoCode: "nf",
    continent: "Oceania",
    flag_1x1: "flags/1x1/nf.svg",
    flag_4x3: "flags/4x3/nf.svg",
    name: "Norfolk Island",
  },
  {
    capital: "Pyongyang",
    isoCode: "kp",
    continent: "Asia",
    flag_1x1: "flags/1x1/kp.svg",
    flag_4x3: "flags/4x3/kp.svg",
    name: "North Korea",
  },
  {
    capital: "Skopje",
    isoCode: "mk",
    continent: "Europe",
    flag_1x1: "flags/1x1/mk.svg",
    flag_4x3: "flags/4x3/mk.svg",
    name: "North Macedonia",
  },
  {
    capital: "Belfast",
    isoCode: "gb-nir",
    continent: "Europe",
    flag_1x1: "flags/1x1/gb-nir.svg",
    flag_4x3: "flags/4x3/gb-nir.svg",
    name: "Northern Ireland",
  },
  {
    capital: "Saipan",
    isoCode: "mp",
    continent: "Oceania",
    flag_1x1: "flags/1x1/mp.svg",
    flag_4x3: "flags/4x3/mp.svg",
    name: "Northern Mariana Islands",
  },
  {
    capital: "Oslo",
    isoCode: "no",
    continent: "Europe",
    flag_1x1: "flags/1x1/no.svg",
    flag_4x3: "flags/4x3/no.svg",
    name: "Norway",
  },
  {
    capital: "Muscat",
    isoCode: "om",
    continent: "Asia",
    flag_1x1: "flags/1x1/om.svg",
    flag_4x3: "flags/4x3/om.svg",
    name: "Oman",
  },
  {
    capital: "Islamabad",
    isoCode: "pk",
    continent: "Asia",
    flag_1x1: "flags/1x1/pk.svg",
    flag_4x3: "flags/4x3/pk.svg",
    name: "Pakistan",
  },
  {
    capital: "Ngerulmud",
    isoCode: "pw",
    continent: "Oceania",
    flag_1x1: "flags/1x1/pw.svg",
    flag_4x3: "flags/4x3/pw.svg",
    name: "Palau",
  },
  {
    capital: "Panama City",
    isoCode: "pa",
    continent: "North America",
    flag_1x1: "flags/1x1/pa.svg",
    flag_4x3: "flags/4x3/pa.svg",
    name: "Panama",
  },
  {
    capital: "Port Moresby",
    isoCode: "pg",
    continent: "Oceania",
    flag_1x1: "flags/1x1/pg.svg",
    flag_4x3: "flags/4x3/pg.svg",
    name: "Papua New Guinea",
  },
  {
    capital: "Asunción",
    isoCode: "py",
    continent: "South America",
    flag_1x1: "flags/1x1/py.svg",
    flag_4x3: "flags/4x3/py.svg",
    name: "Paraguay",
  },
  {
    capital: "Lima",
    isoCode: "pe",
    continent: "South America",
    flag_1x1: "flags/1x1/pe.svg",
    flag_4x3: "flags/4x3/pe.svg",
    name: "Peru",
  },
  {
    capital: "Manila",
    isoCode: "ph",
    continent: "Asia",
    flag_1x1: "flags/1x1/ph.svg",
    flag_4x3: "flags/4x3/ph.svg",
    name: "Philippines",
  },
  {
    capital: "Adamstown",
    isoCode: "pn",
    continent: "Oceania",
    flag_1x1: "flags/1x1/pn.svg",
    flag_4x3: "flags/4x3/pn.svg",
    name: "Pitcairn",
  },
  {
    capital: "Warsaw",
    isoCode: "pl",
    continent: "Europe",
    flag_1x1: "flags/1x1/pl.svg",
    flag_4x3: "flags/4x3/pl.svg",
    name: "Poland",
  },
  {
    capital: "Lisbon",
    isoCode: "pt",
    continent: "Europe",
    flag_1x1: "flags/1x1/pt.svg",
    flag_4x3: "flags/4x3/pt.svg",
    name: "Portugal",
  },
  {
    capital: "San Juan",
    isoCode: "pr",
    continent: "North America",
    flag_1x1: "flags/1x1/pr.svg",
    flag_4x3: "flags/4x3/pr.svg",
    name: "Puerto Rico",
  },
  {
    capital: "Doha",
    isoCode: "qa",
    continent: "Asia",
    flag_1x1: "flags/1x1/qa.svg",
    flag_4x3: "flags/4x3/qa.svg",
    name: "Qatar",
  },
  {
    capital: "Brazzaville",
    isoCode: "cg",
    continent: "Africa",
    flag_1x1: "flags/1x1/cg.svg",
    flag_4x3: "flags/4x3/cg.svg",
    name: "Republic of the Congo",
  },
  {
    capital: "Bucharest",
    isoCode: "ro",
    continent: "Europe",
    flag_1x1: "flags/1x1/ro.svg",
    flag_4x3: "flags/4x3/ro.svg",
    name: "Romania",
  },
  {
    capital: "Moscow",
    isoCode: "ru",
    continent: "Europe",
    flag_1x1: "flags/1x1/ru.svg",
    flag_4x3: "flags/4x3/ru.svg",
    name: "Russia",
  },
  {
    capital: "Kigali",
    isoCode: "rw",
    continent: "Africa",
    flag_1x1: "flags/1x1/rw.svg",
    flag_4x3: "flags/4x3/rw.svg",
    name: "Rwanda",
  },
  {
    capital: "Saint-Denis",
    isoCode: "re",
    continent: "Africa",
    flag_1x1: "flags/1x1/re.svg",
    flag_4x3: "flags/4x3/re.svg",
    name: "Réunion",
  },
  {
    capital: "Jamestown",
    isoCode: "sh-hl",
    continent: "Africa",
    flag_1x1: "flags/1x1/sh-hl.svg",
    flag_4x3: "flags/4x3/sh-hl.svg",
    name: "Saint Helena",
  },
  {
    capital: "Basseterre",
    isoCode: "kn",
    continent: "North America",
    flag_1x1: "flags/1x1/kn.svg",
    flag_4x3: "flags/4x3/kn.svg",
    name: "Saint Kitts and Nevis",
  },
  {
    capital: "Castries",
    isoCode: "lc",
    continent: "North America",
    flag_1x1: "flags/1x1/lc.svg",
    flag_4x3: "flags/4x3/lc.svg",
    name: "Saint Lucia",
  },
  {
    capital: "Kingstown",
    isoCode: "vc",
    continent: "North America",
    flag_1x1: "flags/1x1/vc.svg",
    flag_4x3: "flags/4x3/vc.svg",
    name: "Saint Vincent and the Grenadines",
  },
  {
    capital: "Apia",
    isoCode: "ws",
    continent: "Oceania",
    flag_1x1: "flags/1x1/ws.svg",
    flag_4x3: "flags/4x3/ws.svg",
    name: "Samoa",
  },
  {
    capital: "San Marino",
    isoCode: "sm",
    continent: "Europe",
    flag_1x1: "flags/1x1/sm.svg",
    flag_4x3: "flags/4x3/sm.svg",
    name: "San Marino",
  },
  {
    capital: "São Tomé",
    isoCode: "st",
    continent: "Africa",
    flag_1x1: "flags/1x1/st.svg",
    flag_4x3: "flags/4x3/st.svg",
    name: "Sao Tome and Principe",
  },
  {
    capital: "Riyadh",
    isoCode: "sa",
    continent: "Asia",
    flag_1x1: "flags/1x1/sa.svg",
    flag_4x3: "flags/4x3/sa.svg",
    name: "Saudi Arabia",
  },
  {
    capital: "Edinburgh",
    isoCode: "gb-sct",
    continent: "Europe",
    flag_1x1: "flags/1x1/gb-sct.svg",
    flag_4x3: "flags/4x3/gb-sct.svg",
    name: "Scotland",
  },
  {
    capital: "Dakar",
    isoCode: "sn",
    continent: "Africa",
    flag_1x1: "flags/1x1/sn.svg",
    flag_4x3: "flags/4x3/sn.svg",
    name: "Senegal",
  },
  {
    capital: "Belgrade",
    isoCode: "rs",
    continent: "Europe",
    flag_1x1: "flags/1x1/rs.svg",
    flag_4x3: "flags/4x3/rs.svg",
    name: "Serbia",
  },
  {
    capital: "Victoria",
    isoCode: "sc",
    continent: "Africa",
    flag_1x1: "flags/1x1/sc.svg",
    flag_4x3: "flags/4x3/sc.svg",
    name: "Seychelles",
  },
  {
    capital: "Freetown",
    isoCode: "sl",
    continent: "Africa",
    flag_1x1: "flags/1x1/sl.svg",
    flag_4x3: "flags/4x3/sl.svg",
    name: "Sierra Leone",
  },
  {
    capital: "Singapore",
    isoCode: "sg",
    continent: "Asia",
    flag_1x1: "flags/1x1/sg.svg",
    flag_4x3: "flags/4x3/sg.svg",
    name: "Singapore",
  },
  {
    capital: "Philipsburg",
    isoCode: "sx",
    continent: "North America",
    flag_1x1: "flags/1x1/sx.svg",
    flag_4x3: "flags/4x3/sx.svg",
    name: "Sint Maarten",
  },
  {
    capital: "Bratislava",
    isoCode: "sk",
    continent: "Europe",
    flag_1x1: "flags/1x1/sk.svg",
    flag_4x3: "flags/4x3/sk.svg",
    name: "Slovakia",
  },
  {
    capital: "Ljubljana",
    isoCode: "si",
    continent: "Europe",
    flag_1x1: "flags/1x1/si.svg",
    flag_4x3: "flags/4x3/si.svg",
    name: "Slovenia",
  },
  {
    capital: "Honiara",
    isoCode: "sb",
    continent: "Oceania",
    flag_1x1: "flags/1x1/sb.svg",
    flag_4x3: "flags/4x3/sb.svg",
    name: "Solomon Islands",
  },
  {
    capital: "Mogadishu",
    isoCode: "so",
    continent: "Africa",
    flag_1x1: "flags/1x1/so.svg",
    flag_4x3: "flags/4x3/so.svg",
    name: "Somalia",
  },
  {
    capital: "Pretoria",
    isoCode: "za",
    continent: "Africa",
    flag_1x1: "flags/1x1/za.svg",
    flag_4x3: "flags/4x3/za.svg",
    name: "South Africa",
  },
  {
    capital: "Seoul",
    isoCode: "kr",
    continent: "Asia",
    flag_1x1: "flags/1x1/kr.svg",
    flag_4x3: "flags/4x3/kr.svg",
    name: "South Korea",
  },
  {
    capital: "Juba",
    isoCode: "ss",
    continent: "Africa",
    flag_1x1: "flags/1x1/ss.svg",
    flag_4x3: "flags/4x3/ss.svg",
    name: "South Sudan",
  },
  {
    capital: "Madrid",
    isoCode: "es",
    continent: "Europe",
    flag_1x1: "flags/1x1/es.svg",
    flag_4x3: "flags/4x3/es.svg",
    name: "Spain",
  },
  {
    capital: "Sri Jayawardenepura Kotte, Colombo",
    isoCode: "lk",
    continent: "Asia",
    flag_1x1: "flags/1x1/lk.svg",
    flag_4x3: "flags/4x3/lk.svg",
    name: "Sri Lanka",
  },
  {
    capital: "Ramallah",
    isoCode: "ps",
    continent: "Asia",
    flag_1x1: "flags/1x1/ps.svg",
    flag_4x3: "flags/4x3/ps.svg",
    name: "State of Palestine",
  },
  {
    capital: "Khartoum",
    isoCode: "sd",
    continent: "Africa",
    flag_1x1: "flags/1x1/sd.svg",
    flag_4x3: "flags/4x3/sd.svg",
    name: "Sudan",
  },
  {
    capital: "Paramaribo",
    isoCode: "sr",
    continent: "South America",
    flag_1x1: "flags/1x1/sr.svg",
    flag_4x3: "flags/4x3/sr.svg",
    name: "Suriname",
  },
  {
    capital: "Stockholm",
    isoCode: "se",
    continent: "Europe",
    flag_1x1: "flags/1x1/se.svg",
    flag_4x3: "flags/4x3/se.svg",
    name: "Sweden",
  },
  {
    capital: "Bern",
    isoCode: "ch",
    continent: "Europe",
    flag_1x1: "flags/1x1/ch.svg",
    flag_4x3: "flags/4x3/ch.svg",
    name: "Switzerland",
  },
  {
    capital: "Damascus",
    isoCode: "sy",
    continent: "Asia",
    flag_1x1: "flags/1x1/sy.svg",
    flag_4x3: "flags/4x3/sy.svg",
    name: "Syria",
  },
  {
    capital: "Taipei",
    isoCode: "tw",
    continent: "Asia",
    flag_1x1: "flags/1x1/tw.svg",
    flag_4x3: "flags/4x3/tw.svg",
    name: "Taiwan",
  },
  {
    capital: "Dushanbe",
    isoCode: "tj",
    continent: "Asia",
    flag_1x1: "flags/1x1/tj.svg",
    flag_4x3: "flags/4x3/tj.svg",
    name: "Tajikistan",
  },
  {
    capital: "Dodoma",
    isoCode: "tz",
    continent: "Africa",
    flag_1x1: "flags/1x1/tz.svg",
    flag_4x3: "flags/4x3/tz.svg",
    name: "Tanzania",
  },
  {
    capital: "Bangkok",
    isoCode: "th",
    continent: "Asia",
    flag_1x1: "flags/1x1/th.svg",
    flag_4x3: "flags/4x3/th.svg",
    name: "Thailand",
  },
  {
    capital: "Dili",
    isoCode: "tl",
    continent: "Asia",
    flag_1x1: "flags/1x1/tl.svg",
    flag_4x3: "flags/4x3/tl.svg",
    name: "Timor-Leste",
  },
  {
    capital: "Lomé",
    isoCode: "tg",
    continent: "Africa",
    flag_1x1: "flags/1x1/tg.svg",
    flag_4x3: "flags/4x3/tg.svg",
    name: "Togo",
  },
  {
    capital: "Nukunonu, Atafu,Tokelau",
    isoCode: "tk",
    continent: "Oceania",
    flag_1x1: "flags/1x1/tk.svg",
    flag_4x3: "flags/4x3/tk.svg",
    name: "Tokelau",
  },
  {
    capital: "Nukuʻalofa",
    isoCode: "to",
    continent: "Oceania",
    flag_1x1: "flags/1x1/to.svg",
    flag_4x3: "flags/4x3/to.svg",
    name: "Tonga",
  },
  {
    capital: "Port of Spain",
    isoCode: "tt",
    continent: "South America",
    flag_1x1: "flags/1x1/tt.svg",
    flag_4x3: "flags/4x3/tt.svg",
    name: "Trinidad and Tobago",
  },
  {
    capital: "Edinburgh of the Seven Seas",
    isoCode: "sh-ta",
    continent: "Africa",
    flag_1x1: "flags/1x1/sh-ta.svg",
    flag_4x3: "flags/4x3/sh-ta.svg",
    name: "Tristan da Cunha",
  },
  {
    capital: "Tunis",
    isoCode: "tn",
    continent: "Africa",
    flag_1x1: "flags/1x1/tn.svg",
    flag_4x3: "flags/4x3/tn.svg",
    name: "Tunisia",
  },
  {
    capital: "Ashgabat",
    isoCode: "tm",
    continent: "Asia",
    flag_1x1: "flags/1x1/tm.svg",
    flag_4x3: "flags/4x3/tm.svg",
    name: "Turkmenistan",
  },
  {
    capital: "Cockburn Town",
    isoCode: "tc",
    continent: "North America",
    flag_1x1: "flags/1x1/tc.svg",
    flag_4x3: "flags/4x3/tc.svg",
    name: "Turks and Caicos Islands",
  },
  {
    capital: "Funafuti",
    isoCode: "tv",
    continent: "Oceania",
    flag_1x1: "flags/1x1/tv.svg",
    flag_4x3: "flags/4x3/tv.svg",
    name: "Tuvalu",
  },
  {
    capital: "Ankara",
    isoCode: "tr",
    continent: "Asia",
    flag_1x1: "flags/1x1/tr.svg",
    flag_4x3: "flags/4x3/tr.svg",
    name: "Türkiye",
  },
  {
    capital: "Kampala",
    isoCode: "ug",
    continent: "Africa",
    flag_1x1: "flags/1x1/ug.svg",
    flag_4x3: "flags/4x3/ug.svg",
    name: "Uganda",
  },
  {
    capital: "Kiev",
    isoCode: "ua",
    continent: "Europe",
    flag_1x1: "flags/1x1/ua.svg",
    flag_4x3: "flags/4x3/ua.svg",
    name: "Ukraine",
  },
  {
    capital: "Abu Dhabi",
    isoCode: "ae",
    continent: "Asia",
    flag_1x1: "flags/1x1/ae.svg",
    flag_4x3: "flags/4x3/ae.svg",
    name: "United Arab Emirates",
  },
  {
    capital: "London",
    isoCode: "gb",
    continent: "Europe",
    flag_1x1: "flags/1x1/gb.svg",
    flag_4x3: "flags/4x3/gb.svg",
    name: "United Kingdom",
  },
  {
    isoCode: "un",
    flag_1x1: "flags/1x1/un.svg",
    flag_4x3: "flags/4x3/un.svg",
    name: "United Nations",
  },
  {
    capital: "Washington, D.C.",
    isoCode: "us",
    continent: "North America",
    flag_1x1: "flags/1x1/us.svg",
    flag_4x3: "flags/4x3/us.svg",
    name: "United States of America",
  },
  {
    capital: "Montevideo",
    isoCode: "uy",
    continent: "South America",
    flag_1x1: "flags/1x1/uy.svg",
    flag_4x3: "flags/4x3/uy.svg",
    name: "Uruguay",
  },
  {
    capital: "Tashkent",
    isoCode: "uz",
    continent: "Asia",
    flag_1x1: "flags/1x1/uz.svg",
    flag_4x3: "flags/4x3/uz.svg",
    name: "Uzbekistan",
  },
  {
    capital: "Port Vila",
    isoCode: "vu",
    continent: "Oceania",
    flag_1x1: "flags/1x1/vu.svg",
    flag_4x3: "flags/4x3/vu.svg",
    name: "Vanuatu",
  },
  {
    capital: "Caracas",
    isoCode: "ve",
    continent: "South America",
    flag_1x1: "flags/1x1/ve.svg",
    flag_4x3: "flags/4x3/ve.svg",
    name: "Venezuela",
  },
  {
    capital: "Hanoi",
    isoCode: "vn",
    continent: "Asia",
    flag_1x1: "flags/1x1/vn.svg",
    flag_4x3: "flags/4x3/vn.svg",
    name: "Vietnam",
  },
  {
    capital: "Road Town",
    isoCode: "vg",
    continent: "North America",
    flag_1x1: "flags/1x1/vg.svg",
    flag_4x3: "flags/4x3/vg.svg",
    name: "Virgin Islands (British)",
  },
  {
    capital: "Charlotte Amalie",
    isoCode: "vi",
    continent: "North America",
    flag_1x1: "flags/1x1/vi.svg",
    flag_4x3: "flags/4x3/vi.svg",
    name: "Virgin Islands (U.S.)",
  },
  {
    capital: "Cardiff",
    isoCode: "gb-wls",
    continent: "Europe",
    flag_1x1: "flags/1x1/gb-wls.svg",
    flag_4x3: "flags/4x3/gb-wls.svg",
    name: "Wales",
  },
  {
    capital: "Mata-Utu",
    isoCode: "wf",
    continent: "Oceania",
    flag_1x1: "flags/1x1/wf.svg",
    flag_4x3: "flags/4x3/wf.svg",
    name: "Wallis and Futuna",
  },
  {
    capital: "Laayoune",
    isoCode: "eh",
    continent: "Africa",
    flag_1x1: "flags/1x1/eh.svg",
    flag_4x3: "flags/4x3/eh.svg",
    name: "Western Sahara",
  },
  {
    capital: "Sana'a",
    isoCode: "ye",
    continent: "Asia",
    flag_1x1: "flags/1x1/ye.svg",
    flag_4x3: "flags/4x3/ye.svg",
    name: "Yemen",
  },
  {
    capital: "Lusaka",
    isoCode: "zm",
    continent: "Africa",
    flag_1x1: "flags/1x1/zm.svg",
    flag_4x3: "flags/4x3/zm.svg",
    name: "Zambia",
  },
  {
    capital: "Harare",
    isoCode: "zw",
    continent: "Africa",
    flag_1x1: "flags/1x1/zw.svg",
    flag_4x3: "flags/4x3/zw.svg",
    name: "Zimbabwe",
  },
];

// export default countries;
const tableBody = document.querySelector("#countriesTable tbody");

let i = 1;

countries.forEach((country) => {
  const row = document.createElement("tr");
  row.innerHTML = `
      <td>${i}</td>
      <td>${country.name}</td>
      <td>${country.capital}</td>
      <td>${country.flag_1x1}</td>
      <td>${country.isoCode}</td>
      <td>${country.continent}</td>
    `;
  tableBody.appendChild(row);
  i++;
});